export interface CityOption {
  value: string
  state: string
}

// Top US cities by population. Inlined so autocomplete runs fully client-side
// without a network call. Free-typed values outside this list are still valid.
export const US_CITIES: CityOption[] = [
  { value: 'New York', state: 'NY' },
  { value: 'Los Angeles', state: 'CA' },
  { value: 'Chicago', state: 'IL' },
  { value: 'Houston', state: 'TX' },
  { value: 'Phoenix', state: 'AZ' },
  { value: 'Philadelphia', state: 'PA' },
  { value: 'San Antonio', state: 'TX' },
  { value: 'San Diego', state: 'CA' },
  { value: 'Dallas', state: 'TX' },
  { value: 'San Jose', state: 'CA' },
  { value: 'Austin', state: 'TX' },
  { value: 'Jacksonville', state: 'FL' },
  { value: 'Fort Worth', state: 'TX' },
  { value: 'Columbus', state: 'OH' },
  { value: 'Indianapolis', state: 'IN' },
  { value: 'Charlotte', state: 'NC' },
  { value: 'San Francisco', state: 'CA' },
  { value: 'Seattle', state: 'WA' },
  { value: 'Denver', state: 'CO' },
  { value: 'Washington', state: 'DC' },
  { value: 'Nashville', state: 'TN' },
  { value: 'Oklahoma City', state: 'OK' },
  { value: 'El Paso', state: 'TX' },
  { value: 'Boston', state: 'MA' },
  { value: 'Portland', state: 'OR' },
  { value: 'Las Vegas', state: 'NV' },
  { value: 'Detroit', state: 'MI' },
  { value: 'Memphis', state: 'TN' },
  { value: 'Louisville', state: 'KY' },
  { value: 'Baltimore', state: 'MD' },
  { value: 'Milwaukee', state: 'WI' },
  { value: 'Albuquerque', state: 'NM' },
  { value: 'Tucson', state: 'AZ' },
  { value: 'Fresno', state: 'CA' },
  { value: 'Mesa', state: 'AZ' },
  { value: 'Sacramento', state: 'CA' },
  { value: 'Atlanta', state: 'GA' },
  { value: 'Kansas City', state: 'MO' },
  { value: 'Colorado Springs', state: 'CO' },
  { value: 'Omaha', state: 'NE' },
  { value: 'Raleigh', state: 'NC' },
  { value: 'Miami', state: 'FL' },
  { value: 'Long Beach', state: 'CA' },
  { value: 'Virginia Beach', state: 'VA' },
  { value: 'Oakland', state: 'CA' },
  { value: 'Minneapolis', state: 'MN' },
  { value: 'Tulsa', state: 'OK' },
  { value: 'Arlington', state: 'TX' },
  { value: 'Tampa', state: 'FL' },
  { value: 'New Orleans', state: 'LA' },
  { value: 'Wichita', state: 'KS' },
  { value: 'Cleveland', state: 'OH' },
  { value: 'Bakersfield', state: 'CA' },
  { value: 'Aurora', state: 'CO' },
  { value: 'Anaheim', state: 'CA' },
  { value: 'Honolulu', state: 'HI' },
  { value: 'Santa Ana', state: 'CA' },
  { value: 'Riverside', state: 'CA' },
  { value: 'Corpus Christi', state: 'TX' },
  { value: 'Lexington', state: 'KY' },
  { value: 'Stockton', state: 'CA' },
  { value: 'Henderson', state: 'NV' },
  { value: 'Saint Paul', state: 'MN' },
  { value: 'St. Louis', state: 'MO' },
  { value: 'Cincinnati', state: 'OH' },
  { value: 'Pittsburgh', state: 'PA' },
  { value: 'Greensboro', state: 'NC' },
  { value: 'Anchorage', state: 'AK' },
  { value: 'Plano', state: 'TX' },
  { value: 'Lincoln', state: 'NE' },
  { value: 'Orlando', state: 'FL' },
  { value: 'Irvine', state: 'CA' },
  { value: 'Newark', state: 'NJ' },
  { value: 'Toledo', state: 'OH' },
  { value: 'Durham', state: 'NC' },
  { value: 'Chula Vista', state: 'CA' },
  { value: 'Fort Wayne', state: 'IN' },
  { value: 'Jersey City', state: 'NJ' },
  { value: 'St. Petersburg', state: 'FL' },
  { value: 'Laredo', state: 'TX' },
  { value: 'Madison', state: 'WI' },
  { value: 'Chandler', state: 'AZ' },
  { value: 'Buffalo', state: 'NY' },
  { value: 'Lubbock', state: 'TX' },
  { value: 'Scottsdale', state: 'AZ' },
  { value: 'Reno', state: 'NV' },
  { value: 'Glendale', state: 'AZ' },
  { value: 'Gilbert', state: 'AZ' },
  { value: 'Winston-Salem', state: 'NC' },
  { value: 'North Las Vegas', state: 'NV' },
  { value: 'Norfolk', state: 'VA' },
  { value: 'Chesapeake', state: 'VA' },
  { value: 'Garland', state: 'TX' },
  { value: 'Irving', state: 'TX' },
  { value: 'Hialeah', state: 'FL' },
  { value: 'Fremont', state: 'CA' },
  { value: 'Boise', state: 'ID' },
  { value: 'Richmond', state: 'VA' },
  { value: 'Baton Rouge', state: 'LA' },
  { value: 'Spokane', state: 'WA' },
  { value: 'Des Moines', state: 'IA' },
  { value: 'Tacoma', state: 'WA' },
  { value: 'San Bernardino', state: 'CA' },
  { value: 'Modesto', state: 'CA' },
  { value: 'Fontana', state: 'CA' },
  { value: 'Santa Clarita', state: 'CA' },
  { value: 'Birmingham', state: 'AL' },
  { value: 'Oxnard', state: 'CA' },
  { value: 'Fayetteville', state: 'NC' },
  { value: 'Moreno Valley', state: 'CA' },
  { value: 'Rochester', state: 'NY' },
  { value: 'Glendale', state: 'CA' },
  { value: 'Huntington Beach', state: 'CA' },
  { value: 'Salt Lake City', state: 'UT' },
  { value: 'Grand Rapids', state: 'MI' },
  { value: 'Amarillo', state: 'TX' },
  { value: 'Yonkers', state: 'NY' },
  { value: 'Aurora', state: 'IL' },
  { value: 'Montgomery', state: 'AL' },
  { value: 'Akron', state: 'OH' },
  { value: 'Little Rock', state: 'AR' },
  { value: 'Huntsville', state: 'AL' },
  { value: 'Augusta', state: 'GA' },
  { value: 'Port St. Lucie', state: 'FL' },
  { value: 'Grand Prairie', state: 'TX' },
  { value: 'Columbus', state: 'GA' },
  { value: 'Tallahassee', state: 'FL' },
  { value: 'Overland Park', state: 'KS' },
  { value: 'Tempe', state: 'AZ' },
  { value: 'McKinney', state: 'TX' },
  { value: 'Mobile', state: 'AL' },
  { value: 'Cape Coral', state: 'FL' },
  { value: 'Shreveport', state: 'LA' },
  { value: 'Frisco', state: 'TX' },
  { value: 'Knoxville', state: 'TN' },
  { value: 'Worcester', state: 'MA' },
  { value: 'Brownsville', state: 'TX' },
  { value: 'Vancouver', state: 'WA' },
  { value: 'Fort Lauderdale', state: 'FL' },
  { value: 'Sioux Falls', state: 'SD' },
  { value: 'Ontario', state: 'CA' },
  { value: 'Chattanooga', state: 'TN' },
  { value: 'Providence', state: 'RI' },
  { value: 'Newport News', state: 'VA' },
  { value: 'Rancho Cucamonga', state: 'CA' },
  { value: 'Santa Rosa', state: 'CA' },
  { value: 'Peoria', state: 'AZ' },
  { value: 'Oceanside', state: 'CA' },
  { value: 'Elk Grove', state: 'CA' },
  { value: 'Salem', state: 'OR' },
  { value: 'Pembroke Pines', state: 'FL' },
  { value: 'Eugene', state: 'OR' },
  { value: 'Garden Grove', state: 'CA' },
  { value: 'Cary', state: 'NC' },
  { value: 'Fort Collins', state: 'CO' },
  { value: 'Corona', state: 'CA' },
  { value: 'Springfield', state: 'MO' },
  { value: 'Jackson', state: 'MS' },
  { value: 'Alexandria', state: 'VA' },
  { value: 'Hayward', state: 'CA' },
  { value: 'Clarksville', state: 'TN' },
  { value: 'Lakewood', state: 'CO' },
  { value: 'Lancaster', state: 'CA' },
  { value: 'Salinas', state: 'CA' },
  { value: 'Palmdale', state: 'CA' },
  { value: 'Hollywood', state: 'FL' },
  { value: 'Springfield', state: 'MA' },
  { value: 'Macon', state: 'GA' },
  { value: 'Kansas City', state: 'KS' },
  { value: 'Sunnyvale', state: 'CA' },
  { value: 'Pomona', state: 'CA' },
  { value: 'Killeen', state: 'TX' },
  { value: 'Escondido', state: 'CA' },
  { value: 'Pasadena', state: 'TX' },
  { value: 'Naperville', state: 'IL' },
  { value: 'Bellevue', state: 'WA' },
  { value: 'Joliet', state: 'IL' },
  { value: 'Murfreesboro', state: 'TN' },
  { value: 'Midland', state: 'TX' },
  { value: 'Rockford', state: 'IL' },
  { value: 'Paterson', state: 'NJ' },
  { value: 'Savannah', state: 'GA' },
  { value: 'Bridgeport', state: 'CT' },
  { value: 'Torrance', state: 'CA' },
  { value: 'McAllen', state: 'TX' },
  { value: 'Syracuse', state: 'NY' },
  { value: 'Surprise', state: 'AZ' },
  { value: 'Denton', state: 'TX' },
  { value: 'Roseville', state: 'CA' },
  { value: 'Thornton', state: 'CO' },
  { value: 'Miramar', state: 'FL' },
  { value: 'Pasadena', state: 'CA' },
  { value: 'Mesquite', state: 'TX' },
  { value: 'Olathe', state: 'KS' },
  { value: 'Dayton', state: 'OH' },
]
