// Common job titles biased toward early-career professionals. Inlined for
// client-side autocomplete. Free-typed values outside this list are valid.
export const COMMON_JOB_TITLES: string[] = [
  // Software, data, infra
  'Software Engineer',
  'Senior Software Engineer',
  'Staff Software Engineer',
  'Principal Engineer',
  'Software Developer',
  'Frontend Engineer',
  'Backend Engineer',
  'Full Stack Engineer',
  'Mobile Developer',
  'iOS Developer',
  'Android Developer',
  'Web Developer',
  'Engineering Manager',
  'Site Reliability Engineer',
  'DevOps Engineer',
  'Platform Engineer',
  'Infrastructure Engineer',
  'Cloud Engineer',
  'Machine Learning Engineer',
  'Data Engineer',
  'Data Scientist',
  'Data Analyst',
  'Business Intelligence Analyst',
  'Systems Analyst',
  'Security Engineer',
  'Security Analyst',
  'QA Engineer',
  'Quality Assurance Analyst',
  'Test Engineer',
  'Automation Engineer',
  'Research Scientist',
  'Applied Scientist',

  // Product, design
  'Product Manager',
  'Associate Product Manager',
  'Senior Product Manager',
  'Group Product Manager',
  'Director of Product',
  'Technical Program Manager',
  'Program Manager',
  'Project Manager',
  'Product Owner',
  'Scrum Master',
  'Product Marketing Manager',
  'UX Designer',
  'UI Designer',
  'Product Designer',
  'Visual Designer',
  'Graphic Designer',
  'UX Researcher',
  'Design Manager',
  'Design Director',

  // Sales, customer, marketing
  'Sales Development Representative',
  'Business Development Representative',
  'Account Executive',
  'Senior Account Executive',
  'Account Manager',
  'Enterprise Account Executive',
  'Sales Engineer',
  'Solutions Engineer',
  'Solutions Architect',
  'Customer Success Manager',
  'Customer Success Associate',
  'Customer Support Specialist',
  'Customer Experience Associate',
  'Marketing Manager',
  'Marketing Coordinator',
  'Growth Marketer',
  'Brand Manager',
  'Content Strategist',
  'Content Writer',
  'Copywriter',
  'Editor',
  'SEO Specialist',
  'Digital Marketing Specialist',
  'Email Marketing Specialist',
  'Paid Media Specialist',
  'Social Media Manager',
  'Community Manager',
  'Public Relations Specialist',
  'Communications Manager',
  'Event Coordinator',

  // Finance, consulting, legal
  'Financial Analyst',
  'Senior Financial Analyst',
  'Investment Banking Analyst',
  'Investment Banking Associate',
  'Equity Research Analyst',
  'Credit Analyst',
  'Risk Analyst',
  'Compliance Analyst',
  'Compliance Officer',
  'Tax Analyst',
  'Tax Associate',
  'Auditor',
  'Senior Auditor',
  'Accountant',
  'Senior Accountant',
  'Staff Accountant',
  'Bookkeeper',
  'Controller',
  'Finance Manager',
  'Treasury Analyst',
  'Actuary',
  'Actuarial Analyst',
  'Portfolio Manager',
  'Wealth Advisor',
  'Financial Advisor',
  'Financial Planner',
  'Private Equity Associate',
  'Venture Capital Associate',
  'Management Consultant',
  'Strategy Consultant',
  'Business Consultant',
  'Consultant',
  'Senior Consultant',
  'Associate Consultant',
  'Analyst',
  'Senior Analyst',
  'Research Analyst',
  'Research Associate',
  'Business Analyst',
  'Operations Analyst',
  'Operations Manager',
  'Operations Associate',
  'Lawyer',
  'Associate Attorney',
  'Paralegal',
  'Legal Assistant',
  'Contracts Manager',

  // People, ops, admin
  'Recruiter',
  'Technical Recruiter',
  'HR Generalist',
  'HR Business Partner',
  'People Operations Manager',
  'Talent Acquisition Specialist',
  'Learning and Development Specialist',
  'Benefits Administrator',
  'Payroll Specialist',
  'Office Manager',
  'Executive Assistant',
  'Administrative Assistant',
  'Receptionist',
  'Chief of Staff',
  'Supply Chain Analyst',
  'Logistics Coordinator',
  'Procurement Specialist',
  'Inventory Analyst',
  'Warehouse Manager',

  // Engineering (non-software), architecture
  'Civil Engineer',
  'Mechanical Engineer',
  'Electrical Engineer',
  'Chemical Engineer',
  'Biomedical Engineer',
  'Industrial Engineer',
  'Aerospace Engineer',
  'Environmental Engineer',
  'Structural Engineer',
  'Manufacturing Engineer',
  'Process Engineer',
  'Quality Engineer',
  'Project Engineer',
  'Construction Manager',
  'Architect',
  'Interior Designer',
  'Urban Planner',

  // Healthcare
  'Physician',
  'Medical Resident',
  'Registered Nurse',
  'Nurse Practitioner',
  'Physician Assistant',
  'Pharmacist',
  'Dentist',
  'Veterinarian',
  'Physical Therapist',
  'Occupational Therapist',
  'Speech-Language Pathologist',
  'Medical Assistant',
  'Radiologic Technologist',
  'Clinical Psychologist',
  'Therapist',
  'Counselor',
  'Social Worker',
  'Case Manager',
  'Paramedic',
  'Emergency Medical Technician',

  // Education, research
  'Teacher',
  'Elementary School Teacher',
  'Middle School Teacher',
  'High School Teacher',
  'Substitute Teacher',
  'Professor',
  'Adjunct Professor',
  'Academic Advisor',
  'Tutor',
  'Librarian',
  'Postdoctoral Researcher',
  'Graduate Research Assistant',
  'PhD Candidate',

  // Real estate, insurance, banking
  'Real Estate Agent',
  'Real Estate Broker',
  'Property Manager',
  'Appraiser',
  'Leasing Consultant',
  'Insurance Agent',
  'Claims Adjuster',
  'Underwriter',
  'Loan Officer',
  'Mortgage Broker',
  'Bank Teller',
  'Branch Manager',

  // Public sector, trades, hospitality
  'Police Officer',
  'Firefighter',
  'Military Service Member',
  'Pilot',
  'Flight Attendant',
  'Air Traffic Controller',
  'Electrician',
  'Plumber',
  'Carpenter',
  'HVAC Technician',
  'Mechanic',
  'Automotive Technician',
  'Truck Driver',
  'Delivery Driver',
  'Chef',
  'Sous Chef',
  'Line Cook',
  'Bartender',
  'Barista',
  'Server',
  'Restaurant Manager',
  'Hotel Manager',

  // Retail, general
  'Retail Associate',
  'Retail Manager',
  'Cashier',
  'Sales Associate',
  'Store Manager',
  'Assistant Manager',
  'General Manager',
  'Shift Supervisor',
  'Warehouse Associate',

  // Leadership, independent
  'Director',
  'Senior Director',
  'Vice President',
  'Senior Vice President',
  'Executive Director',
  'Chief Executive Officer',
  'Chief Operating Officer',
  'Chief Financial Officer',
  'Chief Technology Officer',
  'Chief Marketing Officer',
  'Chief People Officer',
  'Founder',
  'Co-Founder',
  'Entrepreneur',
  'Self-Employed',
  'Freelancer',
  'Independent Contractor',
  'Intern',
  'Summer Associate',
  'Apprentice',
  'Student',
]
